# Generated by Django 2.2.4 on 2022-06-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsiteapp', '0002_auto_20220606_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
