# Generated by Django 2.2.4 on 2022-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsiteapp', '0003_auto_20220606_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
