# Generated by Django 2.2.4 on 2022-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsiteapp', '0004_auto_20220608_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='continent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
