# Generated by Django 2.2.4 on 2022-06-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelsiteapp', '0005_trip_continent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='continent',
            new_name='continents',
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='continent', to='travelsiteapp.Trip')),
            ],
        ),
    ]
