# Generated by Django 2.2.4 on 2022-06-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelsiteapp', '0007_auto_20220618_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='continents',
            new_name='continent',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
